In [1]:
!ls ../datas/csv

EcommerceCustomers.csv  USA_Housing.csv         titanic_train.csv
EcommerceCustomers.xlsx titanic_test.csv


In [2]:
import pandas as pd
df= pd.read_csv('../datas/csv/titanic_train.csv')
titanic_y = df['Survived']
titanic_x = df[['Pclass','SibSp','Parch','Embarked', 'Sex']]
titanic_x = pd.get_dummies(titanic_x, columns=['Sex', 'Embarked', 'Pclass'])
titanic_x

SibSp  Parch  Sex_female  Sex_male  Embarked_C  Embarked_Q  Embarked_S  \
0        1      0           0         1           0           0           1   
1        1      0           1         0           1           0           0   
2        0      0           1         0           0           0           1   
3        1      0           1         0           0           0           1   
4        0      0           0         1           0           0           1   
..     ...    ...         ...       ...         ...         ...         ...   
886      0      0           0         1           0           0           1   
887      0      0           1         0           0           0           1   
888      1      2           1         0           0           0           1   
889      0      0           0         1           1           0           0   
890      0      0           0         1           0           1           0   

     Pclass_1  Pclass_2  Pclass_3  
0           0         0         1  
1           1         0         0  
2           0         0         1  
3           1         0         0  
4           0         0         1  
..        ...       ...       ...  
886         0         1         0  
887         1         0         0  
888         0         0         1  
889         1         0         0  
890         0         0         1  

[891 rows x 10 columns]

In [3]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(titanic_x,titanic_y, test_size=0.2)

In [6]:
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()
log.fit(x_train, y_train)

((179, 10), pandas.core.frame.DataFrame, array([0]), numpy.ndarray)

In [11]:
log.coef_, log.intercept_

(array([[-0.19769341, -0.08241154,  1.39559001, -1.3953556 ,  0.30670879,
         -0.10946039, -0.2763734 ,  0.78914913,  0.12449837, -0.9134131 ]]),
 array([0.26288355]))

In [5]:
predictions = log.predict(x_test)	# predict 확인
predictions

array([1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0])

In [12]:
predict_proba = log.predict_proba(x_test)	# 정확도 확인
predict_proba

array([[0.18144344, 0.81855656],
       [0.07961257, 0.92038743],
       [0.92552874, 0.07447126],
       [0.9831867 , 0.0168133 ],
       [0.55831036, 0.44168964],
       [0.53105825, 0.46894175],
       [0.78318884, 0.21681116],
       [0.65014948, 0.34985052],
       [0.2588855 , 0.7411145 ],
       [0.92552874, 0.07447126],
       [0.13101804, 0.86898196],
       [0.34624182, 0.65375818],
       [0.82699126, 0.17300874],
       [0.78318884, 0.21681116],
       [0.13101804, 0.86898196],
       [0.91070378, 0.08929622],
       [0.34624182, 0.65375818],
       [0.69368197, 0.30631803],
       [0.65014948, 0.34985052],
       [0.78318884, 0.21681116],
       [0.19400604, 0.80599396],
       [0.78318884, 0.21681116],
       [0.91070378, 0.08929622],
       [0.70018314, 0.29981686],
       [0.65014948, 0.34985052],
       [0.78318884, 0.21681116],
       [0.91070378, 0.08929622],
       [0.91070378, 0.08929622],
       [0.05984249, 0.94015751],
       [0.4529937 , 0.5470063 ],
       [0.

In [10]:
result = log.predict([[0, 1, 0, 1, 0, 0, 1, 0, 1, 0]])	# titanic_x와 변수 개수 일치 필요.
x_test.shape, type(x_test), result, type(result) # Depend on accuracy

((179, 10), pandas.core.frame.DataFrame, array([0]), numpy.ndarray)

In [7]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, predictions)

0.770949720670391

In [8]:
import pickle
pickle.dump(log, open( "../datas/log.pkl", "wb" ))

In [1]:
!ls ../datas

csv     log.pkl


In [2]:
#Open Other Session and then Upload log.pkl
import pickle
log_picke = pickle.load( open( "../datas/log.pkl", "rb" ) )
from sklearn.linear_model import LogisticRegression
result = log_picke.predict([[0, 1, 0, 1, 0, 0, 1, 0, 1, 0]])
result

array([0])

In [3]:
len([0, 1, 0, 1, 0, 0, 1, 0, 1, 0])

10