## boston dataset from sklearn

In [1]:
from sklearn.model_selection import train_test_split
from sklearn import datasets

In [2]:
boston_dataset = datasets.load_boston()
type(boston_dataset)

sklearn.utils.Bunch

In [3]:
boston_dataset.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [4]:
boston_dataset.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

## get data and label(target) from boston dataset

In [5]:
boston_data = boston_dataset.data
boston_target = boston_dataset.target

### saperate train set and test set

In [6]:
train_boston_data, test_boston_data, train_boston_target, test_boston_target = train_test_split(boston_data, boston_target, test_size=0.2, random_state=0 )
type(train_boston_target[:5]), train_boston_target[:5], test_boston_target[:5], train_boston_data[:5], test_boston_data[:5]

(numpy.ndarray,
 array([26.7, 21.7, 22. , 22.9, 10.4]),
 array([22.6, 50. , 23. ,  8.3, 21.2]),
 array([[3.58090e-01, 0.00000e+00, 6.20000e+00, 1.00000e+00, 5.07000e-01,
         6.95100e+00, 8.85000e+01, 2.86170e+00, 8.00000e+00, 3.07000e+02,
         1.74000e+01, 3.91700e+02, 9.71000e+00],
        [1.58760e-01, 0.00000e+00, 1.08100e+01, 0.00000e+00, 4.13000e-01,
         5.96100e+00, 1.75000e+01, 5.28730e+00, 4.00000e+00, 3.05000e+02,
         1.92000e+01, 3.76940e+02, 9.88000e+00],
        [1.13290e-01, 3.00000e+01, 4.93000e+00, 0.00000e+00, 4.28000e-01,
         6.89700e+00, 5.43000e+01, 6.33610e+00, 6.00000e+00, 3.00000e+02,
         1.66000e+01, 3.91250e+02, 1.13800e+01],
        [8.82900e-02, 1.25000e+01, 7.87000e+00, 0.00000e+00, 5.24000e-01,
         6.01200e+00, 6.66000e+01, 5.56050e+00, 5.00000e+00, 3.11000e+02,
         1.52000e+01, 3.95600e+02, 1.24300e+01],
        [2.59406e+01, 0.00000e+00, 1.81000e+01, 0.00000e+00, 6.79000e-01,
         5.30400e+00, 8.91000e+01, 1.64750

##LinearRegression

In [7]:
from sklearn.linear_model import  LinearRegression

## ?model evaluation
http://mjgim.me/2018/02/28/regression.html, 
https://scikit-learn.org/stable/modules/model_evaluation.html#regression-metrics

##Other Model

In [8]:
result = dict()

linearRegression = LinearRegression()
linearRegression.fit(train_boston_data, train_boston_target)
result['linearRegression'] = linearRegression.score(test_boston_data, test_boston_target) 

from sklearn.linear_model import Ridge
ridge = Ridge()
ridge.fit(train_boston_data, train_boston_target)
result['ridge'] = ridge.score(test_boston_data, test_boston_target) 

ridge_5 = Ridge(alpha=0.5)
ridge_5.fit(train_boston_data, train_boston_target)
result['ridge_5'] = ridge_5.score(test_boston_data, test_boston_target) 

ridge_1 = Ridge(alpha=0.1)
ridge_1.fit(train_boston_data, train_boston_target)
result['ridge_1'] = ridge_1.score(test_boston_data, test_boston_target) 

from sklearn.linear_model import Lasso
lasso = Lasso()
lasso.fit(train_boston_data, train_boston_target)
result['lasso'] = lasso.score(test_boston_data, test_boston_target) 

lasso_1 = Lasso(alpha=1)
lasso_1.fit(train_boston_data, train_boston_target)
result['lasso_1'] = lasso_1.score(test_boston_data, test_boston_target) 

from sklearn.linear_model import ElasticNet
elasticNet = ElasticNet(alpha=0.5)
elasticNet.fit(train_boston_data, train_boston_target)
result['elasticNet'] = elasticNet.score(test_boston_data, test_boston_target) 
