#https://machinelearningmastery.com/calculate-principal-component-analysis-scratch-python/

In [1]:

import numpy as np

from numpy import mean, cov
from numpy.linalg import eig
# define a matrix
# A = array([[1, 2], [3, 4], [5, 6]])
arr = np.array([[95, 95], [90, 95], [80, 75], [60, 70], [40, 35], [80, 80], [95, 90], [30, 25], [15, 10], [60, 70]])
# print('input Data matrix :', arr)
# calculate the mean of each column
# M = mean(A.T, axis=1)
# print('calculate the mean of each column : ', M)
# center columns by subtracting column means
# C = A - M

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
stand_arr = scaler.fit_transform(arr)

print(stand_arr.mean().round(), stand_arr.var())

print('StandardScaler matrix : ',stand_arr)


0.0 1.0
StandardScaler matrix :  [[ 1.13098794  1.05723842]
 [ 0.94558008  1.05723842]
 [ 0.57476436  0.36396733]
 [-0.16686707  0.19064955]
 [-0.90849851 -1.02257487]
 [ 0.57476436  0.5372851 ]
 [ 1.13098794  0.88392065]
 [-1.27931423 -1.36921041]
 [-1.83553781 -1.88916374]
 [-0.16686707  0.19064955]]


In [2]:
# calculate covariance matrix of centered matrix
covarMatrix = cov(stand_arr.T, bias=True)
print('covariance matrix : ', covarMatrix)
# eigendecomposition of covariance matrix
eigvalues, eigvectors = eig(covarMatrix)
print('eigen values : ', eigvalues)
print('eigen vetors : ', eigvectors)
# project data
# P = vectors.T.dot(C.T)
# print(P.T)
pca_data = eigvectors.round().T.dot(stand_arr.T)
print(pca_data.T)

covariance matrix :  [[1.         0.97978022]
 [0.97978022 1.        ]]
eigen values :  [1.97978022 0.02021978]
eigen vetors :  [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[[ 2.18822636 -0.07374952]
 [ 2.0028185   0.11165834]
 [ 0.93873169 -0.21079704]
 [ 0.02378248  0.35751662]
 [-1.93107338 -0.11407636]
 [ 1.11204946 -0.03747926]
 [ 2.01490859 -0.24706729]
 [-2.64852464 -0.08989619]
 [-3.72470154 -0.05362593]
 [ 0.02378248  0.35751662]]


In [15]:
# np.corrcoef(stand_arr.T, pca_data)

array([[ 1.00000000e+00,  9.79780217e-01,  9.94932213e-01,
        -1.00547957e-01],
       [ 9.79780217e-01,  1.00000000e+00,  9.94932213e-01,
         1.00547957e-01],
       [ 9.94932213e-01,  9.94932213e-01,  1.00000000e+00,
         7.59566698e-17],
       [-1.00547957e-01,  1.00547957e-01,  7.59566698e-17,
         1.00000000e+00]])

In [4]:
from scipy.stats.stats import pearsonr   
pearsonr(np.round(pca_data.T[:,0]), pca_data.T[:,1])

(0.010984383784128348, 0.9759745594421864)

In [ ]:
np.correlate(stand_arr.T, pca_data)

In [16]:
from sklearn.decomposition import PCA
pca = PCA()
# fit on data
# pca.fit(stand_arr)
# access values and vectors
# print(pca.components_)
# transform data
pca_result = pca.fit_transform(stand_arr)
print(pca.components_)
print(pca.explained_variance_)
pca_result.var(), pca_result.mean() , pca_result

[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
[2.1997558  0.02246643]


(0.9999999999999998, 1.9428902930940238e-17, array([[-1.5473097 , -0.05214879],
        [-1.41620654,  0.07895437],
        [-0.66378354, -0.14905602],
        [-0.01681675,  0.25280243],
        [ 1.36547508, -0.08066417],
        [-0.78633772, -0.02650184],
        [-1.42475553, -0.17470296],
        [ 1.87278973, -0.0635662 ],
        [ 2.63376172, -0.03791926],
        [-0.01681675,  0.25280243]]))

In [6]:
# ?PCA