#statsmodels.api with OLS

In [0]:
import statsmodels.api as sm
import numpy as np
all_data = [
 [0,2,6],
 [1,3,9],
 [2,4,11.5],
 [3,5,14.5],
 ] 
ndarray = np.array(all_data)
x_data = ndarray[:,:-1]
y_data = ndarray[:,-1]
x_data, y_data

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


(array([[0., 2.],
        [1., 3.],
        [2., 4.],
        [3., 5.]]), array([ 6. ,  9. , 11.5, 14.5]))

In [0]:
sm_constant = sm.add_constant(x_data)
estimate = sm.OLS(y_data, sm_constant)
results = estimate.fit()
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.999
Model:                            OLS   Adj. R-squared:                  0.998
Method:                 Least Squares   F-statistic:                     1568.
Date:                Sun, 17 May 2020   Prob (F-statistic):           0.000637
Time:                        09:06:46   Log-Likelihood:                 3.0883
No. Observations:                   4   AIC:                            -2.177
Df Residuals:                       2   BIC:                            -3.404
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.0833      0.065     16.783      0.0

/usr/local/lib/python3.6/dist-packages/statsmodels/stats/stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 4 samples were given.
  "samples were given." % int(n), ValueWarning)


In [0]:
results.params, type(results.params)

(array([1.08333333, 0.31666667, 2.48333333]), numpy.ndarray)

In [0]:
results.params[0], results.params[1], results.params[2]

(1.083333333333333, 0.3166666666666682, 2.483333333333333)

In [0]:
results.params[0]+(results.params[1]*2)+(results.params[2]*4)

11.650000000000002

In [0]:
results.params[0]+(results.params[1]*4)+(results.params[2]*7)

19.733333333333334

In [0]:
from sklearn.model_selection import train_test_split
from sklearn import datasets

In [0]:
boston_dataset = datasets.load_boston()
type(boston_dataset)

sklearn.utils.Bunch

In [0]:
boston_dataset.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [0]:
print(boston_dataset.DESCR)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [0]:
boston_dataset.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [0]:
boston_dataset.target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [0]:
import pandas as pd

In [0]:
boston_df = pd.DataFrame(boston_dataset.data, columns=boston_dataset.feature_names)
boston_df['Median Value'] = boston_dataset.target
boston_df

CRIM    ZN  INDUS  CHAS  ...  PTRATIO       B  LSTAT  Median Value
0    0.00632  18.0   2.31   0.0  ...     15.3  396.90   4.98          24.0
1    0.02731   0.0   7.07   0.0  ...     17.8  396.90   9.14          21.6
2    0.02729   0.0   7.07   0.0  ...     17.8  392.83   4.03          34.7
3    0.03237   0.0   2.18   0.0  ...     18.7  394.63   2.94          33.4
4    0.06905   0.0   2.18   0.0  ...     18.7  396.90   5.33          36.2
..       ...   ...    ...   ...  ...      ...     ...    ...           ...
501  0.06263   0.0  11.93   0.0  ...     21.0  391.99   9.67          22.4
502  0.04527   0.0  11.93   0.0  ...     21.0  396.90   9.08          20.6
503  0.06076   0.0  11.93   0.0  ...     21.0  396.90   5.64          23.9
504  0.10959   0.0  11.93   0.0  ...     21.0  393.45   6.48          22.0
505  0.04741   0.0  11.93   0.0  ...     21.0  396.90   7.88          11.9

[506 rows x 14 columns]

In [0]:
boston_df.to_csv('boston_df.csv', index = False, header=True)

In [0]:
boston_dataset.feature_names.shape

(13,)

#statsmodels with boston dataset

In [0]:
import statsmodels.api as sm									
sm_constant = sm.add_constant(boston_dataset.data)
estimate = sm.OLS(boston_dataset.target, sm_constant)
print(estimate.fit().summary())


                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.741
Model:                            OLS   Adj. R-squared:                  0.734
Method:                 Least Squares   F-statistic:                     108.1
Date:                Sun, 17 May 2020   Prob (F-statistic):          6.72e-135
Time:                        09:06:47   Log-Likelihood:                -1498.8
No. Observations:                 506   AIC:                             3026.
Df Residuals:                     492   BIC:                             3085.
Df Model:                          13                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         36.4595      5.103      7.144      0.0

In [0]:
import statsmodels.api as sm
variables = list(boston_df.columns)
y = 'Median Value'
x = [var for var in variables if var not in y ]
# estimate = sm.OLS(boston_dataset.target, boston_dataset.data)
estimate = sm.OLS(boston_df[y], boston_df[x])
estimate = estimate.fit()
print(estimate.summary())

                                 OLS Regression Results                                
Dep. Variable:           Median Value   R-squared (uncentered):                   0.959
Model:                            OLS   Adj. R-squared (uncentered):              0.958
Method:                 Least Squares   F-statistic:                              891.3
Date:                Sun, 17 May 2020   Prob (F-statistic):                        0.00
Time:                        09:06:47   Log-Likelihood:                         -1523.8
No. Observations:                 506   AIC:                                      3074.
Df Residuals:                     493   BIC:                                      3128.
Df Model:                          13                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

In [0]:
import statsmodels.api as sm
sm_constant = sm.add_constant(boston_df[x])
estimate = sm.OLS(boston_df[y], sm_constant)
print(estimate.fit().summary())

                            OLS Regression Results                            
Dep. Variable:           Median Value   R-squared:                       0.741
Model:                            OLS   Adj. R-squared:                  0.734
Method:                 Least Squares   F-statistic:                     108.1
Date:                Sun, 17 May 2020   Prob (F-statistic):          6.72e-135
Time:                        09:06:47   Log-Likelihood:                -1498.8
No. Observations:                 506   AIC:                             3026.
Df Residuals:                     492   BIC:                             3085.
Df Model:                          13                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         36.4595      5.103      7.144      0.0

In [0]:
import statsmodels.api as sm
sm_constant = sm.add_constant(boston_df[x])
estimate = sm.OLS(boston_df[y], sm_constant)
print(estimate.fit().summary())

                            OLS Regression Results                            
Dep. Variable:           Median Value   R-squared:                       0.741
Model:                            OLS   Adj. R-squared:                  0.734
Method:                 Least Squares   F-statistic:                     108.1
Date:                Sun, 17 May 2020   Prob (F-statistic):          6.72e-135
Time:                        09:06:47   Log-Likelihood:                -1498.8
No. Observations:                 506   AIC:                             3026.
Df Residuals:                     492   BIC:                             3085.
Df Model:                          13                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         36.4595      5.103      7.144      0.0

# R-squared

In [0]:
from sklearn import metrics
import numpy as np

# 예시
predict_data = [1, 2, 3, 4, 5, 7, 9, 10]
true_data = [1, 10, 3, 3, 9, 7, 8, 10]

print('MAE:',metrics.mean_absolute_error(true_data, predict_data))  # 기본
print('MSE:',metrics.mean_squared_error(true_data, predict_data))
print('RMSE:', np.sqrt(metrics.mean_squared_error(true_data, predict_data)))
print('R2 Score:',metrics.r2_score(true_data, predict_data)) # 1에 가까울 수록 좋음.