In [1]:
from sklearn import datasets
import numpy as np

In [2]:
iris = datasets.load_iris()

In [3]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
x = iris.data

In [5]:
y = iris.target

In [6]:
np.unique(y)

array([0, 1, 2])

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x,y, random_state=777, \
                                                    test_size = 0.3, stratify=y)

In [11]:
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()
log.fit(x_train, y_train)

LogisticRegression()

In [16]:
log.coef_, log.intercept_

(array([[-0.43048348,  0.78888065, -2.31646974, -0.9169996 ],
        [ 0.47654833, -0.35885378, -0.23933683, -0.72046633],
        [-0.04606485, -0.43002686,  2.55580657,  1.63746593]]),
 array([  9.55547417,   2.28629345, -11.84176762]))

In [20]:
y_pred = log.predict(x_test)	# predict 확인
y_pred

array([0, 1, 0, 1, 1, 1, 1, 2, 2, 0, 2, 2, 1, 2, 0, 1, 1, 2, 1, 2, 2, 0,
       2, 0, 2, 2, 1, 2, 0, 1, 1, 2, 0, 1, 0, 0, 1, 0, 2, 2, 0, 0, 0, 0,
       2])

In [21]:
predict_proba = log.predict_proba(x_test)	# 정확도 확인
predict_proba

array([[9.81690590e-01, 1.83093444e-02, 6.58326993e-08],
       [4.08155581e-03, 7.87575439e-01, 2.08343005e-01],
       [9.78590691e-01, 2.14092186e-02, 9.04035746e-08],
       [7.97545503e-02, 9.12293456e-01, 7.95199392e-03],
       [2.81420595e-01, 7.16788688e-01, 1.79071637e-03],
       [1.04568445e-02, 5.63631385e-01, 4.25911771e-01],
       [9.70148062e-02, 8.88738367e-01, 1.42468271e-02],
       [2.06042924e-07, 6.14370983e-03, 9.93856084e-01],
       [5.28009449e-04, 2.97739893e-01, 7.01732098e-01],
       [9.83167477e-01, 1.68325020e-02, 2.05050440e-08],
       [3.29182400e-05, 2.53484704e-02, 9.74618611e-01],
       [9.53407132e-04, 2.54303423e-01, 7.44743170e-01],
       [2.58268630e-02, 9.00848738e-01, 7.33243986e-02],
       [1.86567798e-06, 2.40296406e-02, 9.75968494e-01],
       [9.67409635e-01, 3.25902273e-02, 1.38164887e-07],
       [7.56417854e-03, 7.91469811e-01, 2.00966010e-01],
       [1.36104812e-02, 7.49744355e-01, 2.36645164e-01],
       [1.61266638e-05, 3.24919

In [34]:
import numpy as np
np.sum(predict_proba, axis=1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
y_pred[0], predict_proba[0], predict_proba[0].sum, np.around(predict_proba[0], decimals=4)

(0,
 array([9.81690590e-01, 1.83093444e-02, 6.58326993e-08]),
 <function ndarray.sum>,
 array([0.9817, 0.0183, 0.    ]))

In [37]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.9333333333333333